export const influencerData = [
  {
    id: 1,
    image: '/instagram1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 2,
    image: '/instagram2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 3,
    image: '/instagram3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 4,
    image: '/instagram1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 5,
    image: '/instagram2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 6,
    image: '/instagram3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 7,
    image: '/instagram1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 8,
    image: '/instagram2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 9,
    image: '/instagram3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 10,
    image: '/instagram3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'instagram',
    isSelected: false,
    isCart: false,
  },
  {
    id: 11,
    image: '/facebook1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 12,
    image: '/facebook2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 13,
    image: '/facebook3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 14,
    image: '/facebook1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 15,
    image: '/facebook2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 16,
    image: '/facebook3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 17,
    image: '/facebook1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 18,
    image: '/facebook1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 19,
    image: '/facebook2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 20,
    image: '/facebook3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'facebook',
    isSelected: false,
    isCart: false,
  },
  {
    id: 21,
    image: '/tiktok1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 22,
    image: '/tiktok2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 23,
    image: '/tiktok3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 24,
    image: '/tiktok1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 25,
    image: '/tiktok2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 26,
    image: '/tiktok3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 27,
    image: '/tiktok3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 28,
    image: '/tiktok1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 29,
    image: '/tiktok2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 30,
    image: '/tiktok3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'tiktok',
    isSelected: false,
    isCart: false,
  },
  {
    id: 32,
    image: '/youtube2.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 33,
    image: '/youtube3.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 31,
    image: '/youtube1.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 34,
    image: '/youtube2.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 35,
    image: '/youtube3.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 36,
    image: '/youtube1.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 37,
    image: '/youtube1.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 38,
    image: '/youtube2.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 39,
    image: '/youtube3.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 40,
    image: '/youtube1.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'youtube',
    isSelected: false,
    isCart: false,
  },
  {
    id: 41,
    image: '/instagram1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 42,
    image: '/instagram2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 43,
    image: '/instagram3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 44,
    image: '/instagram1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 45,
    image: '/instagram2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 46,
    image: '/instagram3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 47,
    image: '/instagram3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 48,
    image: '/instagram1.png',
    name: 'Shola Adeboye',
    handle: '@sholaboye',
    followers: '25.4K',
    views: '5.9K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 49,
    image: '/instagram2.png',
    name: 'Promise Eli',
    handle: '@promeli',
    followers: '112K',
    views: '50.5K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
  {
    id: 50,
    image: '/instagram3.png',
    name: 'Dave Steeve',
    handle: '@davesteeve',
    followers: '155.4K',
    views: '22.9K',
    social: 'twitter',
    isSelected: false,
    isCart: false,
  },
];
